### ISSUE TITLE
Fallback CLZ functions give incorrect results

### ISSUE THREAD

**Issue by craigbarnes** [davidgarland/circa#32]
The `return` line for each function is missing the bitwise not operation. In [`u32_clz`](https://github.com/davidgarland/circa/blob/fefba996e37436ab07d30f0f739a1c135278993d/src/h/bits.h#L247), for example:

```
return u32_pop(n);
```

...should be:

```
return u32_pop(~n);
//             ^
```

Otherwise it returns the bitwise compliment of what `__builtin_clz()` would return -- e.g. `u32_clz(1)` returns `1` instead of `31`.

**Comment by davidgarland** [comment]
Good catch, thanks for finding this! Should be fixed here: https://github.com/davidgarland/circa/commit/dc397bb00fd74cd0f657de01c8a2b084b67fa739

**Comment by davidgarland** [comment]
Tested as of the commit https://github.com/davidgarland/circa/commit/fba315a574757fa895dbdd57931376dea18708b0; it's as simple as doing ```C
#undef __GNUC__
#include <circa.h>
#define __GNUC__
``` inside of `tests/test.c` to disable Circa's use of builtins-- doing this yielded no errors with the unit test, so both this and #31 should be decisively fixed now.
