### ISSUE TITLE
Optimize `bits.h` functions slightly

### ISSUE THREAD

**Issue by davidgarland** [davidgarland/circa#35]
This entails:
- Using the "proper" intrinsics by actually checking `sizeof` to avoid subtraction or needless casting.
- Implementing better fallbacks for u##_pop where ## < 32.
- Implementing better fallbacks for u##_ctz where ## < 32.
- Implementing better u##_div10 where ## < 32.

**Comment by craigbarnes** [comment]
For the first point, [this macro] may be useful, at least for selecting the best builtin for u32/u64.

[this macro]: https://github.com/craigbarnes/dte/blob/3a923743903ef487dc3436f7d3778bc9d1ccd22f/src/util/bit.h#L12-L19

**Comment by davidgarland** [comment]
Nice, I'll be sure to give that a try then, thanks! :)

It seems like there actually aren't 8-bit/16-bit variants for a lot of random builtins, so that seems about as good as it gets for some things. On the other hand some tweaking may need to be done to adjust for the 8-bit and 16-bit cases where adjustment is needed (clz and such.)

**Comment by craigbarnes** [comment]
> It seems like there actually aren't 8-bit/16-bit variants for a lot of random builtins

To be honest, I think there's a reason for that. Bit scan operations are mostly used for performance reasons and the potential gain from using them on 8-bit types is pretty non-existent. 16-bit types are also pretty rare to see in most codebases. Personally, I would remove the `u8` and `u16` functions and add some for `size_t`.

**Comment by davidgarland** [comment]
There already are size_t functions in the form of the `usz` functions, unless I misunderstand what you mean?

**Comment by craigbarnes** [comment]
> There already are `size_t` functions in the form of the `usz` functions

Ah yeah, my mistake.

> Also, I don't much see the reason for removing them-- they are static inline functions

Yeah, that's a good point. No harm in providing them if they have zero size overhead.

**Comment by davidgarland** [comment]
Should be done now. https://github.com/davidgarland/circa/commit/03b2f46e92d108e8d5888d9d9e8a3c8bd369a98c
