### ISSUE TITLE
Memory leaks on allocation failure

### ISSUE THREAD

**Issue by craigbarnes** [davidgarland/circa#38]
I was just looking at the code in `seqmap.c` and noticed that if `malloc`/`calloc`/etc. return NULL, the code just sets an error code and returns early, without freeing any of the allocations made further up the function body. [Some](https://github.com/davidgarland/circa/blob/259ccd66f5c06483c75d000160072b7c73d60bfa/src/c/seqmap.c#L173-L178) [of](https://github.com/davidgarland/circa/blob/259ccd66f5c06483c75d000160072b7c73d60bfa/src/c/seqmap.c#L196-L201) [the](https://github.com/davidgarland/circa/blob/259ccd66f5c06483c75d000160072b7c73d60bfa/src/c/seqmap.c#L34-L38) [allocations](https://github.com/davidgarland/circa/blob/259ccd66f5c06483c75d000160072b7c73d60bfa/src/c/seqmap.c#L145-L149) are also grouped and then checked together afterwards in a single `if` statement, which allows the first to succeed (and leak) but the second to fail.

**Comment by davidgarland** [comment]
Good catch, I'll take a look at handling this a bit better-- somehow this had never really crossed my mind. OOM errors tend to be rare, so I'm still not very experienced with handling them "properly."

**Comment by davidgarland** [comment]
By the way, while I'm at it: Do you think I should make things like argument `NULL` checks a `if` instead of `ce_guard` to prevent segfaults? Or should I just program around it and make sure to always propagate `CE` upwards before doing something that can't tolerate a `NULL` argument? I feel like the second is probably more error prone but also more performant, idk.

**Comment by davidgarland** [comment]
I think this should fix (most? all of?) the problems: https://github.com/davidgarland/circa/commit/ba93343b9cd8a57091d463996608c4c8dbaa5e34

**Comment by craigbarnes** [comment]
> Do you think I should make things like argument `NULL` checks a if instead of `ce_guard` to prevent segfaults?

I guess it depends on how likely it is to happen and whether the function is internal or public. The performance cost can be reduced a bit by using `__builtin_expect()`.

One thing I would definitely do though is add the `nonnull` attribute to any function parameter you expect to never be `NULL`. It's the most useful attribute by far IMO. GCC and Clang give warnings at compile-time for constants, or at run-time for non-constants when using `-fsanitize=undefined`. It also helps the Clang static analyzer and `clang-tidy` produce better checks and error messages. I think Coverity uses it too.

> I think this should fix (most? all of?) the problems: ba93343

Looks good to me.

**Comment by davidgarland** [comment]
Alright, cool! Thanks again. :)
