### ISSUE TITLE
Implement String Templating

### ISSUE THREAD

**Issue by davidgarland** [davidgarland/circa#4]
Right now there's no sprintf equivalent for Circa's strings. A wrapper around sprintf could probably be easily made and will be done, but perhaps it's possible to do it in a more performant way.

**Comment by craigbarnes** [comment]
If you're targeting C99 or later, you can use `snprintf(NULL, 0, "example: %d", 123)` to get the required size and then do the call as normal after any resizing/reallocing. It's not exactly highly optimized but it can be done in 20 lines of [code](https://github.com/craigbarnes/dte/blob/d3f92e816f397809533575ea6f9b69cea4374e3c/src/util/string.c#L65-L85).

**Comment by davidgarland** [comment]
Done. :) https://github.com/davidgarland/circa/commit/e23d583657217fcdb5fdd47be0207336482a2d04
